<?php

use BlueHeron\Blog\Model\Post;
use Magento\Framework\View\Element\Template;
$postViewModel = $block->getData('post_view_model');


$post = $block->getData('post');
?>

<a href="<?= $postViewModel->getPostUrl($post); ?>">
    <h3><?= $post->getData('title'); ?></h3>
</a>
<p>
    <span class="author">Blue Heron</span>
    <span class="published-date"><?= $block->formatDate($post->getData('creation_time')); ?></span>
</p>
<p>
    <?= $post->getData('content'); ?>
</p>