<?php

declare(strict_types=1);

use BlueHeron\Blog\Model\Post;
use BlueHeron\Blog\ViewModel\Post\PostView;
use Magento\Framework\View\Element\Template;

$postView = $block->getData('post_view_model');
$post = $postView->getPost();

?>

<h1><?= $post->getData('title'); ?></h1>

<p>
    <span class="author">Blue Heron</span>
    <span class="published-date"><?= $block->formatDate($post->getData('creation_time')); ?></span>
</p>
<p>
    <?= $post->getData('content'); ?>
</p>